### ISSUE TITLE
Default Marc Reader

### ISSUE THREAD

**Issue by jrochkind** [traject-project/traject#56]
reader default logic should pick the best reader depending on environmental context, from pure-ruby MarcReader vs Marc4JReader. 

* If not Jruby, MarcReader
* If Jruby and Marc4JReader is available, Marc4JReader. 
* If Jruby and Marc4JReader not available, choose MarcReader, but print out a warning suggesting installation of Marc4JReader (and/or adding it to Gemfile if using Gemfile) for better performance. 

Default logic of course only comes into play if the user hasn't explicitly set a reader class. If they have, just trust they know what they want. (Note since configuration files are ruby, you could write your own logic to explicitly set different configuration depending on platform/version if you wanted, just put some `if`is in there!)

**Comment by jrochkind** [comment]
I _think_ I now remember @billdueber a while ago determining that, to his ability to measure, even under JRuby, the MarcReader was just as fast as the Marc4J reader. So there's no need for this, we can just use the MarcReader all the time. 

Does that match your memory, Bill?  If so, we can close this without action.

**Comment by billdueber** [comment]
That's correct. marc4j is still useful for those that needs its weirdness
(e.g., whatever system it is that splits records across two records or
whatever it is) or for folks that need marc8 support.

On Thu, Jan 15, 2015 at 4:37 PM, Jonathan Rochkind <notifications@github.com
> wrote:

> I *think* I now remember @billdueber <https://github.com/billdueber> a
> while ago determining that, to his ability to measure, even under JRuby,
> the MarcReader was just as fast as the Marc4J reader. So there's no need
> for this, we can just use the MarcReader all the time.
>
> Does that match your memory, Bill? If so, we can close this without
> action.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traject-project/traject/issues/56#issuecomment-70166671>
> .
>



-- 
Bill Dueber
Library Systems Programmer
University of Michigan Library

**Comment by jrochkind** [comment]
For the record, the pure-ruby MarcReader actually supports marc8 encoding fine now, I added that some months ago.
