### ISSUE TITLE
update embedded solrj?

### ISSUE THREAD

**Issue by jrochkind** [traject-project/traject#58]
traject includes a vendored solrj.jar.  Update to latest solr release for traject 2.0?  I believe latest solrj will always work with old solrs, that's generally been something Solr has been committed to (although you can't always use the binary transmission format with old Solrs and new SolrJ's, you can still use the new SolrJ if you don't tell it to use the binary transmission format). 

https://github.com/traject-project/traject/tree/master/vendor/solrj

**Comment by billdueber** [comment]
This belongs in the traject-solrj_writer gem now, and I think updating to the very latest .jar files is probably wise. I'll look into compatibility.

**Comment by jrochkind** [comment]
Note I had a rake task for automatically downloading and uploading to latest .jars -- not sure if the rake task was migrated over (or removed from this gem as it should be!). 

Note also that the tests (at least used to) have an ENV setting that made them work against a live solr. If that migrated over too -- if you update to latest jars, then run the tests against a live Solr, and they pass, that seems pretty good. For extra credit, test against several different versions of a live Solr, including a really old one we want to make sure we're still supporting (you still have one of those around? :) )
