### ISSUE TITLE
Very slightly different gem releases for jruby vs MRI

### ISSUE THREAD

**Issue by jrochkind** [traject-project/traject#60]
If we agree on the goal -- get traject working under MRI, but it's not going to be high-performance, and we will _strongly_ recommend people use jruby (with solrj writer and marc4j reader) for real non-toy production use....

I am a bit unhappy that we're made installation under recommended jruby configuration slightly harder , by requiring you to manually install the ruby-marc4J gem (or manually add it to your Gemfile). 

But it strikes me this could be fairly easily rectified. While in general I'm scared of having different code relases for Jruby and MRI, as I think it can lead to maintenance confusion nightmare.... What if there was a different release for jruby but the _only difference_ was that the jruby gemspec included an extra line for a dependency under jruby that is incompatible with MRI -- that is, ruby-marc4j?  Seems plausible. We could rig something up so the MRI gemspec automatically has a line or two extra added to it to make a jruby gemspec, and that'd be the only difference between MRI and jruby releases.

**Comment by jrochkind** [comment]
We're doing something different, we decided this wasn't needed, we can write everything ruby-platform-agnostic for the default.

**Comment by billdueber** [comment]
We've decided to not go this route, yes?

**Comment by jrochkind** [comment]
yep, I thought I closed the issue when  I commented yesterday, must have pressed the wrong button. closed!
