### ISSUE TITLE
2.0: Undefined package ref in Traject::SolrJsonWriter#record_id_from_context

### ISSUE THREAD

**Issue by barmintor** [traject-project/traject#80]
https://github.com/traject-project/traject/blob/dev-2.0/lib/traject/solr_json_writer.rb#L172

I think the package reference is unintentional- I removed it in a monkey patch with no apparent harm done.

**Comment by jrochkind** [comment]
Hey, thanks for the report. I'm not sure what you mean by 'package reference' there. Can you possibly give us a failing test case (or just code that reproduces the problem even if you haven't packaged it as a test case)?

**Comment by jrochkind** [comment]
Or failing that, the code from your monkey patch would be help me understand what you're referring to! But code that reproduces the problem would be best!

**Comment by jrochkind** [comment]
Ah wait, sorry for posting before carefully thinking, you mean the `package` in `package.context...`. Yeah. 

Bug, and we need to include a test case that fails before the fix when including the fix. Feel free to file a PR with such a failing test case, otherwise me or Bill will get to it.

**Comment by barmintor** [comment]
I'm trying to get this blacklight-marc branch done before I head to
Code4Lib, but I'll put together a PR ASAP. Just wanted to document it!

On Sun, Feb 8, 2015 at 12:40 PM, Jonathan Rochkind <notifications@github.com

**Comment by jrochkind** [comment]
Right on, thanks a lot @barmintor for the report!

**Comment by billdueber** [comment]
Fixed and tests added in #81. Thanks for the bug report, @barmintor!
