### ISSUE TITLE
Make Marc4JReader default on jruby somehow?

### ISSUE THREAD

**Issue by jrochkind** [traject-project/traject#82]
@billdueber  finds that it's about 2x as fast at reading XML on Jruby than the MarcReader. (Not sure if that's MarcReader with nokogiri or not?). 

https://gist.github.com/billdueber/a388b2d0d3aec7f96134

This makes me less happy at it requiring extra setup to use -- for ruby newbies, installing/using gems can be non-trivial, and I want ruby newbies to get high performance out of the box. 

Possible ideas:

* Make traject default to Marc4JReader instead of MarcReader under jruby, and, either one or two of:
    * 1) Make a jruby version of the gem, which is _identical_ *but for* including Marc4JReader in it's gemspec. 
    * 2) Make all versions of traject depend on Marc4JReader in gemspec, but it simply won't be used unless under JRuby (and would raise if you tried).  That would require making Marc4JReader willing to be loaded on MRI -- but doing anything other than loading it would of course raise. 

* Simply warn if they are on JRuby and using MarcReader, log that they should use Marc4JReader instead, but leave them to figure out how to get it set up themselves. (Last resort from my point of view).

**Comment by billdueber** [comment]
Yeah, it was with nokogiri, which isn't as fast under jruby as under MRI.

It feels to me as if you're worrying a lot about people who:

* can install JRuby
* have enough records that the speed difference makes a difference
* can put together a valid indexing file, but
* can do `gem install traject`
* _can't_ manage to do `gem install traject-marc4j_reader`

This seems like a vanishingly small set of people to me. 

An all-inclusive `.jar` could be offered as a gateway solution; let people get started with that and then when they have bought into `traject` and decide they want to get fancier, they can actually install jruby and the associated gems.

**Comment by jrochkind** [comment]
I want traject to work as high performance as we can make it on JRuby out of the box, without having to install something else.  I consider JRuby to be the 'home' platform of traject, we've made it work on other platforms, but we will continue to make sure it works as fast as possible on Jruby and recommend that. 

I want traject to be accessible to those not formerly rubyists. I think they will be able to figure out how to install jruby (although it won't be easy), but having to install and use a gem is one more barrier that doesn't need to be there. 

It isn't just type `gem install traject-marc4_reader`. It's also adding a 'require' statement to your file (one more thing to understand if you're new to ruby) and manually set the writer. Worse, if you are't using Bundler, I think you're doing it wrong, and don't want to be suggesting the wrong way of doing it. I think using Bundler for dependency version control is the only right way to do it, and by providing instructions for that, we've significantly upped the complexity for a not-previously-ruby of getting traject installed as we intend it for high performance. It's gone from "figure out how to get jruby installed (the end)" to "figure out how ruby dependencies work, with bundler, with require statements, etc., remember to configure the Marc4JReader because it's not default."

I'm glad we've gotten traject to work on multiple platforms, but I stand by my concern I voiced when you started down that path -- I think traject on jruby has to work, out of the box, with default configuration and no extra gems, in the high performance manner we intend it to, as high performance as we can get it. You shouldn't have to learn how to do anything extra to get high performance jruby. Anything else is significant barriers for those not expert rubyists using traject, they're going to end up using it slower. 

I think this is reasonable, and I think it's achievable. Can you remind me why you wanted Marc4J in a separate gem in the first place?

**Comment by billdueber** [comment]
OK . I still think the population you're targeting is essentially non-existent, but I'd be happy to be proven wrong and you obviously feel a lot more strongly about this than I do. 

Why don't we explore releasing two gems; I don't think it's that hard. Include `marc4j` and `solrj` in the JRuby specfile and call it a day? I'll look into it tonight.

[BTW, I originally wanted to break out the marc4j stuff because (a) I use it out outside of traject, and (b) I didn't want the release schedule for the .jar files to be tied to traject's release schedule. Ditto with solrj. I know you're all about the tight coupling, but I hate having release schedules in sync when they don't need to be.]

**Comment by jrochkind** [comment]
Really, it's just the principle: Our recommended configuration needs to be the default. Especially on Jruby. I think it's this principle that keeps traject easy to use, and I don't want to violate it. 

Fortunately, I think it's doable. And I'm gonna do it. Do you have any preferences between:

1. include marc4j as a dependency in all traject, but of course you won't be able to use it unless you are jruby.  This can be done simply by removing `spec.platform      = 'java'` from Marc4JReader gem and marc-marc4j gem (or putting Marc4JReader back into traject too). The only downside is even if you aren't on Jruby, you'll be downloading and installing Marc4JReader gem, with a 400KB jar. I don't think that's a big deal, really. 

2. Provide an alternate platform=jruby gemspec for for traject, that includes the marc4jReader dependency. I think this can be done in a fairly automated and DRY way, so the jruby gemspec really is exactly identical but for including the extra dependency. Without _too_ much trouble, but it does require more work, and introduces another layer of things that can go wrong. 

I lean toward 1, because it's less work and simpler, but I suspect you may prefer 2, and I could go with it if you feel strongly.

**Comment by billdueber** [comment]
What would really rankle about removing the 'java' platform is that it implicitly makes a claim that it'll work under any ruby, and it won't.  You're right -- I would prefer the second option. 

Can a gemspec just have a `if spec.platform =~ /java/`... in it? Or do we really need to have multiple gemspecs?

**Comment by jrochkind** [comment]
Logic in a gemspec is run at _build_ time, not at install time or runtime. One way or another, we need to push two different gemspecs to rubygems in order to have different gemspecs for Jruby vs everything else on a gem. 

It doesn't bother me to have an 'implicit claim' that it works on other things, when the docs (and the name of the gem itself!) make clear it does not -- and the only negative consequence if someone does get this 'implicit claim' is the first time they try to use it on anything other than Jruby, they'll get an exception telling them it only works on JRuby. Does not seem like a big deal to me. 

But if it bothers you, I'll try to figure out how to do it the other way.  Clearly different things bother each of us, heh.

**Comment by jrochkind** [comment]
Initial experiments are showing (2) to be even trickier than I thought. I'm gonna sleep on it, but let me know if you reconsider on (1). 

To me it's really not a big deal that some people may accidentally install marc4jreader/ruby-marc4j on MRI, but get an exception with a nicely formatted error message telling them it's JRuby only if they try to use it. 

But then, to you it's not a big deal that people will have to install and configure an extra gem as an extra step to get marc4jreader, obviously different things appear as big deals to us, heh.

**Comment by billdueber** [comment]
Yeah, apparently we've reached the point where the intersection of what we want is roughly zero :-) Although, given how much we've been in sync for most of this project, I think it's safe to blame the ruby packaging systems...

I built up dual .gemspec in #83 that I think will work just fine.

**Comment by jrochkind** [comment]
ha, the ironic thing is the bundler/rubygems dependency management system is probably better than any other platform has got!

**Comment by billdueber** [comment]
This is in the 2.0 rc1. Closing.
