### ISSUE TITLE
Release 2.0.0.rc.1

### ISSUE THREAD

**Issue by billdueber** [traject-project/traject#84]
Barring concerns by @jrochkind, gonna release version 2.0.0rc1 into the wild.

**Comment by jrochkind** [comment]
Sure, do it!

**Comment by jrochkind** [comment]
Merge dev-2.0 into master (and delete dev-2.0 branch) first?

**Comment by billdueber** [comment]
Released as 2.0.0.rc.1 and 2.0.0.rc.1-java

**Comment by jrochkind** [comment]
Hi @billdueber, was that released from dev-2.0 branch, or from master?

**Comment by billdueber** [comment]
dev-2.0 was merged into master, then released from master.

On Wed, Feb 11, 2015 at 11:00 AM, Jonathan Rochkind <
notifications@github.com> wrote:

> Hi @billdueber <https://github.com/billdueber>, was that released from
> dev-2.0 branch, or from master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traject-project/traject/issues/84#issuecomment-73906309>
> .
>



-- 
Bill Dueber
Library Systems Programmer
University of Michigan Library
