### ISSUE TITLE
Add marc-fastxmlwriter to gemspec?

### ISSUE THREAD

**Issue by billdueber** [traject-project/traject#87]
Might be worth doing; it's lightweight and gobs faster.

**Comment by jrochkind** [comment]
Agreed, this makes sense. Maybe even before 2.0 release? Should it be what gets used when you do `serialize_marc(:format => xml)` replacing the existing implementation? I think maybe so?

**Comment by billdueber** [comment]
Addressed in #88. Discussion can take place over there.
