### ISSUE TITLE
Release 2.0.0 ? 

### ISSUE THREAD

**Issue by billdueber** [traject-project/traject#90]
I'm solid -- been running the new code for days. As soon as you're ready, give the word. I'll start working on a release note.

**Comment by billdueber** [comment]
The [traject](https://github.com/traject-project/traject/) maintainers are happy to announce the release of traject version 2.0.0.

Traject is an ETL (extract/transform/load) system designed and optimized for indexing MARC records into Solr. It is similar in functionality to [solrmarc](https://code.google.com/p/solrmarc/), but with everything written in ruby instead of java.

Traject 2.0 brings several notable changes:
* Support for both MRI ("normal") ruby and JRuby
* New Solr JSON writer (for solr versions >=3.2) accessible from MRI and with about 20% better performance than previous indexing.
* New writers for producing tab-delimited/CSV files

The [traject README](https://github.com/traject-project/traject/) and [doc folder](https://github.com/traject-project/traject/tree/master/doc) contain reference information, and we also provide a [sample real-ish configuration](https://github.com/traject-project/traject_sample) to help get you started. The University of Michigan and Hathitrust catalogs are indexed using traject; [their shared configuration](https://github.com/billdueber/ht_traject) provides a (potentially overly-) complex real-life set of configuration files.

**Comment by jrochkind** [comment]
Cool, ideally I'd like to run it at least a few days in production myself. Tonight can be the first.

**Comment by jrochkind** [comment]
(I did, for instance, realize I needed a small update to traject_horizon when I first tried running it with 2.0, it used a method that had been removed from traject for loading jruby)

**Comment by jrochkind** [comment]
(Mention Johns Hopkins Libraries catalog is also indexed with traject? Although my config isn't in an open repo alas)

**Comment by billdueber** [comment]
Would it be worth providing a snapshot, at least of the JH indexes, just for instructional purposes? Or do you think we have most of it covered already?

The Brown stuff is a great simple config -- real life, but not so complex as UMich. I'm glad to be able to point at it.

**Comment by jrochkind** [comment]
The demo config linked to in the README, and at https://github.com/traject-project/traject/blob/master/test/test_support/demo_config.rb, basically is a snapshot of the JH config. (You mean a snapshot of the traject config, not of the Solr indexes, right?)

It's evolved from there, but probably mostly only in ways that make it more confusing without adding much educational value, as a snapshot. 

(I would like it if my code were in openly accessible repositories so people could see what we're actually doing at any point live, but that's not in the cards for the immediate future)

**Comment by jrochkind** [comment]
I've run it over two nights in production (under Jruby), runs fine in about the same amount of time traject 1.x was taking (my bottleneck is mostly export from my ILS). 

I'm ready for a release! +1

**Comment by billdueber** [comment]
OK. I'll do a final run-through tonight, make sure all the subservient gems have the right gemspec, and push it out. Announcements to blacklight, code4lib, solrmarc...anywhere else? Hydra?
